---
# tasks file for security_group
# Meant to be used in a loop with item holding parameters for security group


- name: create security group
  os_security_group:
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"

- name: add rule to security group
  os_security_group_rule:
    security_group: "{{ item.name }}"
    protocol: "{{ item.protocol }}"
    port_range_min: "{{ item.port_range_min }}"
    port_range_max: "{{ item.port_range_max }}"
    remote_ip_prefix: "{{ item.remote_ip_prefix }}"
