- hosts: localhost              # run tasks on local host
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true            # This module takes care of executing the configured facts modules, 
                                # the default is to use the setup module. 
                                # Because of the condition set when ansible_distribution == "Ubuntu"

  roles:
    - role: openstack-dependencies
    # - role: openstack-images            # Uncomment if want to retrieve image information
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    # - role: openstack-volume-snapshot   # Uncomment if want to obtain volume snapshot

- hosts: prototype
  vars_files:
    - host_vars/wordpress.yaml
  gather_facts: true

  roles:
    - role: proxy
    - role: wp-dependencies
    - role: wp-volumes
    - role: wp-docker
    - role: wp-wordpress
