- hosts: localhost
  vars:
    sg_name: quiz_3
    sg_description: "Quiz 3"
    sg_protocol: tcp
    sg_port_min: 80
    sg_port_max: 80
    sg_ip_prefix: 0.0.0.0/0
    instance_name: demo-01
    instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
    instance_key_name: id_alwyn
    instance_flavor: uom.general.1c4g
    instance_az: melbourne-qh2-uom

  tasks:
  - name: Create a security group
    os_security_group:
      name: '{{ sg_name }}'
      description: '{{ sg_description }}'
      state: present

  - name: Create security group rules
    os_security_group_rule:
      security_group: '{{ sg_name }}'
      protocol: '{{ sg_protocol }}'
      port_range_min: '{{ sg_port_min }}'
      port_range_max: '{{ sg_port_max }}'
      remote_ip_prefix: '{{ sg_ip_prefix }}'
      state: present

  - name: Add security group to instance
    os_server:
      name: '{{ instance_name }}'
      image: '{{ instance_image }}'
      key_name: '{{ instance_key_name }}'
      flavor: '{{ instance_flavor }}'
      availability_zone: '{{ instance_az }}'
      security_groups: '{{ sg_name }}'
      timeout: 600
      state: present