- hosts: localhost
  vars:
    volume_name: quiz_2
    volume_size: 10
    volume_az: melbourne-qh2-uom
    instance_name: demo-01

  tasks:
  - name: Create volume on NeCTAR
    os_volume:
      display_name: '{{ volume_name }}'
      size: '{{ volume_size }}'
      availability_zone: '{{ volume_az }}'
      wait: yes
      timeout: 600
      state: present

  - name: Attach volume to instance
    os_server_volume:
      state: present
      server: '{{ instance_name }}'
      volume: '{{ volume_name }}'
