---
# As the instance is behind the University network, your instance will need to add proxy settings 
# to access the internet. Need to amend /etc/environment after launching instances

- name: Add proxy in etc/environment
  become: yes
  blockinfile:
    dest: /etc/environment
    block:  |
      HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      http_proxy=http://wwwproxy.unimelb.edu.au:8000/
      https_proxy=http://wwwproxy.unimelb.edu.au:8000/
      no_proxy="localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"


# Add proxy configuration for docker
- name: Create directory /etc/systemd/system/docker.service.d
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    recurse: yes
    state: directory
   
# http-proxy.conf is copied from var folder and attached to /etc/systemd/system/docker.service.d
- name: Copy http-proxy.conf
  become: yes
  template: 
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
 
# Reload daemon  
- name: reload daemon-reload
  become: yes
  systemd: 
    daemon-reload: yes

# Reload docker service
- name: restart docker
  become: yes
  shell: systemctl restart docker
    
# Reboot the instances to have new proxy settings to take effect
# - name: Reboot a machine
#   become: yes
#   reboot:
#     reboot_timeout: 600