---
# Create services directory on instances
- name: Create harvester directory if it does not exist
  tags: 'directory'
  become: yes
  file:
    path: "{{ harvester_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Harvester Container
  become: yes
  template: src={{ item }}.j2 dest={{ harvester_dir }}/{{ item }}
  with_items:
    - docker-compose.yaml
    - Dockerfile
    - app.py
    - requirements.txt


# Any services that are not defined in the compose file will be removed from the container
# To add more services into the container, just include them in the docker-compose.yaml.j2
- name: Run docker compose to build harvester
  become: yes
  docker_compose:
    project_src: "{{ harvester_dir }}"
    pull: yes
    state: present
    remove_orphans: yes  
    recreate: always
    build: yes
