---
# tasks file for instance


- name: launch instance
  os_server:
    state: present  # create instance
    name: "{{ item.name }}"
    availability_zone: "{{ item.availability_zone }}"
    image: "{{ item.image }}"
    flavor: "{{ item.flavor }}"
    network: "{{ item.network }}"
    security_groups: default
    key_name: "{{ item.key_name }}"  # key pair name
    volumes: ["{{ item.vol_name }}"]  # names of volumes to attach
    auto_ip: yes  # automatic floating IP
    wait: yes  # wait till the instance created
    timeout: 600  #  max waiting time (sec)
