---
- name: create keypairs
  hosts: localhost
  vars_files:
    - vars/access.yaml
  tasks:
    - name: create keypairs
      include_role:
        name: keypair
      loop: "{{ keypaths|dict2items }}"
