---
- name: create security groups
  hosts: localhost
  vars_files:
    - vars/security.yaml
  tasks:
    - name: create security groups
      include_role:
        name: security_group
      loop: "{{ security_groups }}"
