---
- name: create security groups
  hosts: localhost
  tasks:
    - include_vars: host_vars/all.yml
    - name: create security groups
      include_role:
        name: security_group
      loop: "{{ security_groups }}"
