---
# variables for all hosts


availability_zone: melbourne-qh2-uom
image: 215f9775-483c-4e0a-b703-d21a5c966f2e  # NeCTAR Ubuntu 18.04 LTS (Bionic) amd64 (with Docker)
flavor: uom.general.1c4g  # 1 CPU, 4GB RAM, 30GB Drive, Private
network: qh2-uom-internal  # internal instead of public where resources is limited
key_name: common  # pre-created key pair
vol_size: 10  # GB

instances:
  - name: thinkbox1
    vol_name: vol1
    availability_zone: "{{ availability_zone }}"
    image: "{{ image }}"
    flavor: "{{ flavor }}"
    network: "{{ network }}"
    key_name: "{{ key_name }}"
    vol_size: "{{ vol_size }}"

  - name: thinkbox2
    vol_name: vol2
    availability_zone: "{{ availability_zone }}"
    image: "{{ image }}"
    flavor: "{{ flavor }}"
    network: "{{ network }}"
    key_name: "{{ key_name }}"
    vol_size: "{{ vol_size }}"
